/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SignUpRouteImport } from "./routes/sign-up"
import { Route as SignInRouteImport } from "./routes/sign-in"
import { Route as ResetPasswordRouteImport } from "./routes/reset-password"
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password"
import { Route as AccountRouteImport } from "./routes/account"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$"

const SignUpRoute = SignUpRouteImport.update({
    id: "/sign-up",
    path: "/sign-up",
    getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
    id: "/sign-in",
    path: "/sign-in",
    getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
    id: "/reset-password",
    path: "/reset-password",
    getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
    id: "/forgot-password",
    path: "/forgot-password",
    getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
    id: "/account",
    path: "/account",
    getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
    id: "/api/auth/$",
    path: "/api/auth/$",
    getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute
    "/account": typeof AccountRoute
    "/forgot-password": typeof ForgotPasswordRoute
    "/reset-password": typeof ResetPasswordRoute
    "/sign-in": typeof SignInRoute
    "/sign-up": typeof SignUpRoute
    "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
    "/": typeof IndexRoute
    "/account": typeof AccountRoute
    "/forgot-password": typeof ForgotPasswordRoute
    "/reset-password": typeof ResetPasswordRoute
    "/sign-in": typeof SignInRoute
    "/sign-up": typeof SignUpRoute
    "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
    __root__: typeof rootRouteImport
    "/": typeof IndexRoute
    "/account": typeof AccountRoute
    "/forgot-password": typeof ForgotPasswordRoute
    "/reset-password": typeof ResetPasswordRoute
    "/sign-in": typeof SignInRoute
    "/sign-up": typeof SignUpRoute
    "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths:
        | "/"
        | "/account"
        | "/forgot-password"
        | "/reset-password"
        | "/sign-in"
        | "/sign-up"
        | "/api/auth/$"
    fileRoutesByTo: FileRoutesByTo
    to:
        | "/"
        | "/account"
        | "/forgot-password"
        | "/reset-password"
        | "/sign-in"
        | "/sign-up"
        | "/api/auth/$"
    id:
        | "__root__"
        | "/"
        | "/account"
        | "/forgot-password"
        | "/reset-password"
        | "/sign-in"
        | "/sign-up"
        | "/api/auth/$"
    fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    AccountRoute: typeof AccountRoute
    ForgotPasswordRoute: typeof ForgotPasswordRoute
    ResetPasswordRoute: typeof ResetPasswordRoute
    SignInRoute: typeof SignInRoute
    SignUpRoute: typeof SignUpRoute
    ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/sign-up": {
            id: "/sign-up"
            path: "/sign-up"
            fullPath: "/sign-up"
            preLoaderRoute: typeof SignUpRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/sign-in": {
            id: "/sign-in"
            path: "/sign-in"
            fullPath: "/sign-in"
            preLoaderRoute: typeof SignInRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/reset-password": {
            id: "/reset-password"
            path: "/reset-password"
            fullPath: "/reset-password"
            preLoaderRoute: typeof ResetPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/forgot-password": {
            id: "/forgot-password"
            path: "/forgot-password"
            fullPath: "/forgot-password"
            preLoaderRoute: typeof ForgotPasswordRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/account": {
            id: "/account"
            path: "/account"
            fullPath: "/account"
            preLoaderRoute: typeof AccountRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/": {
            id: "/"
            path: "/"
            fullPath: "/"
            preLoaderRoute: typeof IndexRouteImport
            parentRoute: typeof rootRouteImport
        }
        "/api/auth/$": {
            id: "/api/auth/$"
            path: "/api/auth/$"
            fullPath: "/api/auth/$"
            preLoaderRoute: typeof ApiAuthSplatRouteImport
            parentRoute: typeof rootRouteImport
        }
    }
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    AccountRoute: AccountRoute,
    ForgotPasswordRoute: ForgotPasswordRoute,
    ResetPasswordRoute: ResetPasswordRoute,
    SignInRoute: SignInRoute,
    SignUpRoute: SignUpRoute,
    ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
    interface Register {
        ssr: true
        router: Awaited<ReturnType<typeof getRouter>>
    }
}
